spring:
  application:
    name: project
  datasource:
    url: jdbc:mariadb://localhost:3306/eloms
#    username: JADE
#    password: 091216
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false