spring:
  application:
    name: project
  datasource:
    url: jdbc:mariadb://45.76.99.38:3306/eloms
    username: root
    password: GmuV9Xpgc9MShRz
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false