spring:
  application:
    name: project
  datasource:
    url: jdbc:mariadb://localhost:3306/ems
    username: JADE
    password: 091216
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false