spring:
  application:
    name: project
  datasource:
    url: jdbc:mariadb://149.28.22.13:3306/eloms
    username: root
    password: CeZxsAMPFyfwtmYY
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  security:
    user:
      name: admin
      password: pass123